name: Build & Release

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: write
  

env:
  build-version-number: 0.1.${{ github.run_number }}  
    
jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
              
      - name: pkgchk
        uses: tonycknight/pkgchk-action@v1.0.16
    
  
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
              
      - name: Run build
        run: |
            dotnet tool restore
            dotnet build -c Release

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
                      
      - name: Tests
        run: |
          dotnet tool restore
          dotnet test -c Debug --logger "trx;LogFileName=test_results.trx" /p:CollectCoverage=true /p:CoverletOutput=./TestResults/coverage.info /p:CoverletOutputFormat=cobertura

      - name: Consolidate code coverage
        run: |
          dotnet reportgenerator -reports:"./tests/**/coverage.info" -targetdir:"./publish/codecoverage" -reporttypes:"Html"
          dotnet reportgenerator -reports:"./tests/**/coverage.info" -targetdir:"./publish/codecoveragedata" -reporttypes:"Cobertura"

      - name: Archive Test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unit_tests_results
          path: |
            ./tests/**/TestResults/*
            
      - name: Archive Code coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Full_code_coverage_report
          path: ./publish/codecoverage/*.*
                    
      - name: Unit test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit test results
          path: ${{ github.workspace }}/tests/*.tests.unit/TestResults/test_results.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Code coverage summary
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path: ${{ github.workspace }}/publish/codecoveragedata/Cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 0
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
          show_class_names: true
          skip_covered: false
          link_missing_lines: true
          report_name: Code coverage summary

