name: Build & Release

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: write
  packages: write
 

env:
  build-version-number: 0.1.${{ github.run_number }}  
  build-prerelease: false
    
jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
              
      - name: pkgchk
        uses: tonycknight/pkgchk-action@v1.0.16
      
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
              
      - name: Run build
        run: |
            dotnet tool restore
            dotnet build -c Release

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
                      
      - name: Tests
        run: |
          dotnet tool restore
          dotnet test -c Debug --logger "trx;LogFileName=test_results.trx" /p:CollectCoverage=true /p:CoverletOutput=./TestResults/coverage.info /p:CoverletOutputFormat=cobertura

      - name: Consolidate code coverage
        run: |
          dotnet reportgenerator -reports:"./tests/**/coverage.info" -targetdir:"./publish/codecoverage" -reporttypes:"Html"
          dotnet reportgenerator -reports:"./tests/**/coverage.info" -targetdir:"./publish/codecoveragedata" -reporttypes:"Cobertura"

      - name: Archive Test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unit_tests_results
          path: |
            ./tests/**/TestResults/*
            
      - name: Archive Code coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Full_code_coverage_report
          path: ./publish/codecoverage/*.*
                    
      - name: Unit test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit test results
          path: ${{ github.workspace }}/tests/*.tests/TestResults/test_results.trx
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Code coverage summary
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path: ${{ github.workspace }}/publish/codecoveragedata/Cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
          fail_below_threshold: true
          show_line: true
          show_branch: true
          show_missing: true
          show_class_names: true
          skip_covered: false
          link_missing_lines: true
          report_name: Code coverage summary

  packaging:
    name: Build package & Release
    runs-on: ubuntu-latest
    needs:   [ tests, build, sca ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4

      - name: dotnet tool restore
        run: |
          dotnet tool restore
          dotnet restore

      - name: Set Build version
        if: github.ref != 'refs/heads/main'
        run: |
          echo "build-prerelease=true" >> $GITHUB_ENV  
          echo "build-version-number=${{ env.build-version-number }}-preview" >> $GITHUB_ENV
          
      - name: Create Nuget package
        run: dotnet pack ./src/microbroker.client/Microbroker.Client.fsproj -c Release -o ./package/ /p:PackageVersion=${{ env.build-version-number }} /p:Version=${{ env.build-version-number }} /p:AssemblyInformationalVersion=${{ env.build-version-number }}
      
      - name: Push nuget package
        if: github.event_name == 'push'
        run: dotnet nuget push "package/*.nupkg"  --api-key ${{ secrets.NUGET_PAT }} --source "nuget.org"

      - name: Create GH Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
        with:
          tag: v${{ env.build-version-number }}
          prerelease: ${{ env.build-prerelease }}
          generateReleaseNotes: true