name: Pull Request checks

on:
  pull_request:
  
permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: write

jobs:  
  size-label:
    name: Set change size
    runs-on: ubuntu-latest
    steps:
      - name: Set label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "1": "XS",
              "10": "S",
              "20": "M",
              "50": "L",
              "100": "XL"
            }

  pr-scope:
    name: Set PR scope
    runs-on: ubuntu-latest
    needs: [ size-label ]
    steps:
      - uses: actions/labeler@v5
        name: Set label
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  sca:
    uses: ./.github/workflows/sca.yml

  check-style-rules:
    runs-on: ubuntu-latest
    name: Check Style rules
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4                
  
      - name: Style checks
        run: |
            dotnet tool restore    
            dotnet fantomas ./ --check